name: stash_objectbox
version: 4.0.0
publish_to: none
description: >-
  Objectbox storage extension for the stash caching API. Provides support to store caches
  in the Objectbox database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_objectbox

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  path: ^1.8.0
  #stash: ^4.0.0
  stash:
    path: ../stash
  objectbox: ^1.2.1
dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3
  build_runner: ^2.1.5
  #stash_test: ^4.0.0
  stash_test:
    path: ../stash_test
  objectbox_generator: ^1.2.1
  dependency_validator: ^3.1.0