name: stash_objectbox
version: 4.0.2
description: >-
  Objectbox storage extension for the stash API. Provides support to store vaults 
  and caches in a Objectbox database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_objectbox

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  path: ^1.8.1
  stash: ^4.0.1
  #stash:
  #  path: ../stash
  objectbox: ^1.4.1
dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.0
  build_runner: ^2.1.10
  stash_test: ^4.0.1
  #stash_test:
  #  path: ../stash_test
  objectbox_generator: ^1.4.1