name: stash_objectbox
version: 4.3.4
description: >-
  Objectbox storage extension for the stash API. Provides support to store vaults 
  and caches in a Objectbox database
homepage: https://pub.dev/packages/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.7.0
  path: ^1.8.1
  # Other dependencies
  stash: ^4.3.3
  objectbox: ^1.6.2
  flat_buffers: ^2.0.5
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  build_runner: ^2.2.0
  stash_test: ^4.3.3
  objectbox_generator: ^1.6.2