name: stash_objectbox
version: 4.4.0
description: >-
  Objectbox storage extension for the stash API. Provides support to store vaults 
  and caches in a Objectbox database
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.8.0
  path: ^1.8.2
  # Other dependencies
  stash: ^4.3.4
  objectbox: ^1.6.2
  flat_buffers: ^2.0.5
dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  build_runner: ^2.3.2
  stash_test: ^4.3.4
  objectbox_generator: ^1.6.2