name: stash_objectbox
version: 2.0.2
publish_to: none
description: >-
  Objectbox storage extension for the stash caching API. Provides support to store caches
  in the Objectbox database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_objectbox

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  stash: ^2.0.2
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8