name: stash_objectbox
version: 4.1.0
description: >-
  Objectbox storage extension for the stash API. Provides support to store vaults 
  and caches in a Objectbox database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_objectbox

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  path: ^1.8.2
  stash: ^4.0.1
  objectbox: ^1.5.0
  flat_buffers: ^2.0.5
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  build_runner: ^2.1.11
  stash_test: ^4.0.1
  objectbox_generator: ^1.5.0