name: stash_objectbox
version: 3.0.2
#publish_to: none
description: >-
  Objectbox storage extension for the stash caching API. Provides support to store caches
  in the Objectbox database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_objectbox

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  path: ^1.8.0
  stash: ^3.0.1
  #stash:
  #  path: ../stash
  objectbox: ^1.0.0
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.9
  build_runner: ^2.0.5
  stash_test: ^3.0.0
  #stash_test:
  #  path: ../stash_test
  objectbox_generator: ^1.0.0
  dependency_validator: ^3.1.0