name: stash_objectbox
version: 4.6.0
description: >-
  Objectbox storage extension for the stash API. Provides support to store vaults 
  and caches in a Objectbox database
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.8.0
  path: ^1.8.3
  # Other dependencies
  stash: ^4.5.0
  objectbox: ^1.7.2
  flat_buffers: ^2.0.5
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.21.4
  # Other dependencies
  lints: ^2.0.1
  build_runner: ^2.3.3
  stash_test: ^4.5.0
  objectbox_generator: ^1.7.2