name: stash

packages:
  - packages/**

ide:
  intellij:
    false

scripts:
  analyze:
    run: |
      melos exec -- \
        "dart analyze . --fatal-infos"
    description: |
      Run `dart analyze` in all packages.

  format:
    run: |
      melos exec -- \
        "dart format --set-exit-if-changed ."
    description: |
      Run `dart format` in all packages.

  doc:
    run: |
      melos exec -- \
        "dartdoc"
    description: |
      Generate documentation for all packages.

  test:
    run: |
      melos exec -c 1 -- \
        "dart test --concurrency=1 --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib"
    description: |
      Run `dart test` and collects coverage in all packages.

  pana:
    run: |
      melos exec -c 1 -- \
        "../../tool/pana.sh"
    description: |
      Run `pana` in all packages.