name: stash

packages:
  - packages/**

scripts:
  analyze:
    run: |
      melos exec -c 1 -- \
        "dart analyze . --fatal-infos"
    description: |
      Run `dart analyze` in all packages.

  format:
    run: |
      melos exec -c 1 -- \
        "dart format --set-exit-if-changed ."
    description: |
      Run `dart format` in all packages.

  test:
    run: |
      melos exec -c 1 -- \
        "dart test"
    description: |
      Run `dart test` in all packages.

  coverage:
    run: |
      melos exec -c 1 -- \
        "dart test --concurrency=1 --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib"
    description: |
      Collects coverage in all packages.

  doc:
    run: |
      melos exec -c 1 -- \
        "dartdoc"
    description: |
      Generated documentation for all packages.

  lint:
    run: melos run analyze && melos run format
    description: Run all static analysis checks

  verify:
    run: melos run lint && melos run test
    description: Runs static analysis and unit tests