name: stash

packages:
  - packages/**

ide:
  intellij:
    false

scripts:
  upgrade:
    run: |
      melos exec -- \
        "dart pub upgrade"
    description: |
      Run `dart pub upgrade` in all packages.

  outdated:
    run: |
      melos exec -- \
        "dart pub outdated"
    description: |
      Run `dart pub outdated` in all packages.

  analyze:
    run: |
      melos exec -- \
        "dart analyze . --fatal-infos"
    description: |
      Run `dart analyze` in all packages.

  format:
    run: |
      melos exec -- \
        "dart format --set-exit-if-changed ."
    description: |
      Run `dart format` in all packages.

  doc:
    run: |
      melos exec -- \
        "dartdoc"
    description: |
      Generate documentation for all packages.

  test:
    run: |
      melos exec -- \
        "dart test"
    description: |
      Run `dart test` in all packages.

  coverage:
    run: |
      melos exec -c 1 -- \
        "dart test --concurrency=1 --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib"
    description: |
      Run `dart test` and collects coverage in all packages.

  pana:
    run: |
      melos exec -c 1 -- \
        "../../tool/pana.sh"
    description: |
      Run `pana` in all packages.

  codecov:
    run: |
      melos exec -c 1 -- \
        "bash <(curl https://codecov.io/bash) -f coverage/lcov.info -F MELOS_PACKAGE_NAME"
    description: |
      Uploads the code coverage to codecov.