name: stash
version: 1.0.0-dev.1
description: >-
  Standard caching API for Dart. Defines a common mechanism to create, 
  access, update, and remove information from caches. Provides a in memory
  reference implementation
homepage: https://github.com/ivoleitao/stash

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  equatable: ^1.2.0
  time: ^1.3.0
  uuid: ^2.0.4
  quiver: ^2.1.3
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.7
  test_coverage: ^0.4.1
