name: stash
version: 2.0.0-nullsafety.3
description: >-
  Standard caching API for Dart. Defines a common mechanism to create, 
  access, update, and remove information from caches. Provides a in memory
  reference implementation
homepage: https://github.com/ivoleitao/stash

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  time: ^2.0.0
  uuid: ^3.0.3
  quiver: ^3.0.0
  matcher: ^0.12.10
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  # test_coverage: ^0.5.0
