name: stash_test
version: 3.2.1
description: >-
  Provides the testing support needed in order to implement extensions to the base stash
  package
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_test

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  enum_to_string: ^2.0.1 
  equatable: ^2.0.3
  clock: ^1.1.0
  time: ^2.0.0
  test: ^1.17.12
  matcher: ^0.12.11
  stash: ^3.2.2
  #stash:
  #  path: ../stash
dev_dependencies:
  lints: ^1.0.1
  dependency_validator: ^3.1.0