name: stash_test
version: 3.0.0
description: >-
  Provides the testing support needed in order to implement extensions to the base stash
  package
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_test

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  enum_to_string: ^2.0.1 
  equatable: ^2.0.2
  clock: ^1.1.0
  time: ^2.0.0
  test: ^1.17.4
  matcher: ^0.12.10
  stash: ^3.0.0
dev_dependencies:
  pedantic: ^1.11.0