name: stash_test
version: 4.3.2
description: >-
  Provides the testing support needed in order to implement extensions to the base stash
  package
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_test

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  clock: ^1.1.0
  # Other dependencies
  equatable: ^2.0.3
  time: ^2.1.1
  test: ^1.21.4
  stash: ^4.3.1
dev_dependencies:
  lints: ^2.0.0