name: stash_test
version: 4.2.0
description: >-
  Provides the testing support needed in order to implement extensions to the base stash
  package
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_test

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  clock: ^1.1.0
  time: ^2.1.0
  test: ^1.21.1
  stash: ^4.2.0
dev_dependencies:
  lints: ^2.0.0