name: stash_isar
version: 4.3.3
publish_to: none
description: >-
  Isar storage extension for the stash caching API. Provides support to store vaults 
  and caches in the Isar database
homepage: https://pub.dev/packages/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.7.0
  # Other dependencies
  isar: ^3.0.0-dev.13
  stash: ^4.3.3
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  build_runner: ^2.2.0
  isar_generator: ^3.0.0-dev.13
  stash_test: ^4.3.2