name: stash_isar
version: 2.0.2
publish_to: none
description: >-
  Isar storage extension for the stash caching API. Provides support to store caches
  in the Isar database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_isar

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  stash: ^2.0.2
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8