name: stash_isar
version: 4.3.1
publish_to: none
description: >-
  Isar storage extension for the stash caching API. Provides support to store vaults 
  and caches in the Isar database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_isar

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  isar: ^3.0.0-dev.7
  stash: ^4.3.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  build_runner: ^2.1.11
  isar_generator: ^3.0.0-dev.7
  stash_test: ^4.3.0