name: stash_isar
version: 3.2.0
publish_to: none
description: >-
  Isar storage extension for the stash caching API. Provides support to store caches
  in the Isar database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_isar

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  stash: ^3.2.0
  #stash:
  #  path: ../stash
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
  stash_test: ^3.2.0
  #stash_test:
  #  path: ../stash_test
  dependency_validator: ^3.1.0