name: stash_isar
version: 3.0.0-dev.1
publish_to: none
description: >-
  Isar storage extension for the stash caching API. Provides support to store caches
  in the Isar database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_isar

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  stash: ^3.0.0-dev.2
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  #stash_test: ^3.0.0-dev.2
  stash_test:
    path: ../stash_test