name: stash_isar
version: 4.4.0
description: >-
  Isar storage extension for the stash caching API. Provides support to store vaults 
  and caches in the Isar database
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.8.0
  # Other dependencies
  isar: ^3.0.3
  stash: ^4.3.4
dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  build_runner: ^2.3.2
  isar_generator: ^3.0.3
  stash_test: ^4.3.4