name: stash_isar
version: 5.0.0
description: >-
  Isar storage extension for the stash caching API. Provides support to store vaults 
  and caches in the Isar database
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.9.1
  # Other dependencies
  isar: ^3.1.0+1
  stash: ^5.0.0
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.1
  # Other dependencies
  lints: ^2.1.1
  build_runner: ^2.4.5
  isar_generator: ^3.1.0+1
  stash_test: ^4.5.3