name: stash_file
version: 4.4.1
description: >-
  File storage extension for the stash API. Provides support to store vaults 
  and caches in the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.8.0
  path: ^1.8.2
  # Other dependencies
  file: ^6.1.4
  stream_transform: ^2.1.0
  stash: ^4.4.1
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.21.4
  # Other dependencies
  lints: ^2.0.1
  stash_test: ^4.4.1