name: stash_file
version: 4.0.2
description: >-
  File storage extension for the stash API. Provides support to store vaults 
  and caches in the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_file

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  path: ^1.8.1
  file: ^6.1.2
  stream_transform: ^2.0.0
  stash: ^4.0.1
  #stash:
  #  path: ../stash
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  stash_test: ^4.0.1
  #stash_test:
  #  path: ../stash_test