name: stash_file
version: 2.0.2
description: >-
  File storage extension for the stash caching API. Provides support to store caches
  in the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_file

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  file: ^6.1.0
  stream_transform: ^2.0.0
  stash: ^2.0.2
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8