name: stash_dio
version: 3.0.1
publish_to: none
description: >-
  Dio extension for the stash caching API. Provides an interceptor that uses
  Stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_dio

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  equatable: ^2.0.2
  http_parser: ^4.0.0
  crypto: ^3.0.1
  dio: ^4.0.0
  #stash: ^3.0.0
  stash:
    path: ../stash
  #stash_memory: ^3.0.0
  stash_memory:
    path: ../stash_memory
  #stash_hive: ^3.0.0
  stash_hive:
    path: ../stash_hive
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  mocktail: ^0.1.2
  #stash_test: ^3.0.0
  stash_test:
    path: ../stash_test
  #stash_file: ^3.0.0
  stash_file:
    path: ../stash_file