name: stash_dio
version: 5.0.0
description: >-
  Dio extension for the stash API. Provides an interceptor that uses
  stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  http_parser: ^4.0.2
  crypto: ^3.0.3
  dio: ^5.2.1+1
  stash: ^4.5.3
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.24.1
  # Other dependencies
  lints: ^2.1.1
  mocktail: ^0.3.0
  stash_memory: ^4.5.3
  stash_file: ^4.5.3