name: stash_dio
version: 4.3.3
description: >-
  Dio extension for the stash API. Provides an interceptor that uses
  stash as a caching layer for Dio
homepage: https://pub.dev/packages/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  http_parser: ^4.0.1
  crypto: ^3.0.2
  dio: ^4.0.6
  stash: ^4.3.3
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  mocktail: ^0.3.0
  stash_memory: ^4.3.2
  stash_file: ^4.3.2