name: stash_dio
version: 3.1.0
publish_to: none
description: >-
  Dio extension for the stash caching API. Provides an interceptor that uses
  Stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_dio

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  http_parser: ^4.0.0
  crypto: ^3.0.1
  dio: ^4.0.0
  stash: ^3.1.0
  # stash:
  #  path: ../stash
  #stash_memory: ^3.0.1
  stash_memory:
    path: ../stash_memory
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
  mocktail: ^0.1.4
  #stash_file: ^3.0.1
  stash_file:
    path: ../stash_file
  dependency_validator: ^3.1.0