name: stash_dio
version: 4.1.0
publish_to: none
description: >-
  Dio extension for the stash API. Provides an interceptor that uses
  stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_dio

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  http_parser: ^4.0.1
  crypto: ^3.0.2
  dio: ^4.0.6
  stash: ^4.1.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  mocktail: ^0.3.0
  stash_memory: ^4.0.1
  stash_file: ^4.0.1