name: stash_dio
version: 4.0.0
publish_to: none
description: >-
  Dio extension for the stash caching API. Provides an interceptor that uses
  Stash as a caching layer for Dio
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_dio

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  http_parser: ^4.0.0
  crypto: ^3.0.1
  dio: ^4.0.4
  stash: ^4.0.0-dev.2
  #stash:
  #  path: ../stash
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0
  mocktail: ^0.2.0
  stash_memory: ^4.0.0-dev.2
  #stash_memory:
  #  path: ../stash_memory
  stash_file: ^4.0.0-dev.2
  #stash_file:
  #  path: ../stash_file