name: stash_memory
version: 3.0.0-dev.1
description: >-
  Memory storage extension for the stash caching API. Provides support to store caches
  in-memory
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_memory

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  stash: ^3.0.0-dev.1
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  stash_test: ^3.0.0-dev.2