name: stash_memory
version: 4.0.1
description: >-
  Memory storage extension for the stash API. Provides support to store vaults 
  and caches in-memory
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_memory

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  stash: ^4.0.1
  #stash:
  #  path: ../stash
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  stash_test: ^4.0.1
  #stash_test:
  #  path: ../stash_test