name: stash_memory
version: 3.0.2
#publish_to: none
description: >-
  Memory storage extension for the stash caching API. Provides support to store caches
  in-memory
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_memory

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  stash: ^3.0.1
  #stash:
  #  path: ../stash
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.9
  stash_test: ^3.0.0
  #stash_test:
  #  path: ../stash_test
  dependency_validator: ^3.1.0