name: stash_cbl
version: 4.3.4
description: >-
  Couchbase Lite storage extension for the stash API. Provides support to store
  vaults and caches in a Couchbase Lite database.
homepage: https://pub.dev/packages/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  path: ^1.8.1
  # Other dependencies
  cbl: ^2.0.0+0
  stash: ^4.3.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  stash_test: ^4.3.4
  cbl_dart: ^2.1.0
