name: stash_cbl
version: 4.1.0
description: >-
  Couchbase Lite storage extension for the stash API. Provides support to store
  vaults and caches in a Couchbase Lite database.
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_cbl
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cbl: ^1.2.0
  path: ^1.8.2
  stash: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  stash_test: ^4.1.0
  cbl_dart: ^1.1.0+0
