name: stash_hive
version: 3.0.0-dev.2
description: >-
  Hive storage extension for the stash caching API. Provides support to store caches
  in the Hive database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_hive

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  hive: ^2.0.4
  stash: ^3.0.0-dev.2
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
  stash_test: ^3.0.0-dev.3