name: stash_hive
version: 3.2.2
publish_to: none
description: >-
  Hive storage extension for the stash caching API. Provides support to store caches
  in the Hive database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_hive

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  hive: ^2.0.4
  universal_platform: ^1.0.0+1
  #stash: ^3.2.2
  stash:
    path: ../stash
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.12
  #stash_test: ^3.2.1
  stash_test:
    path: ../stash_test
  dependency_validator: ^3.1.0