name: stash_hive
version: 4.1.0
description: >-
  Hive storage extension for the stash caching API. Provides support to store vaults 
  and caches in the Hive database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_hive

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  hive: ^2.2.1
  universal_platform: ^1.0.0+1
  stash: ^4.1.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  stash_test: ^4.0.1