name: stash_hive
version: 4.4.1
description: >-
  Hive storage extension for the stash caching API. Provides support to store vaults 
  and caches in the Hive database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_hive

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.8.0
  # Other dependencies
  hive: ^2.2.3
  universal_platform: ^1.0.0+1
  stash: ^4.4.1
dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  stash_test: ^4.4.1