name: stash_hive
version: 4.3.2
description: >-
  Hive storage extension for the stash caching API. Provides support to store vaults 
  and caches in the Hive database
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_hive

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.7.0
  # Other dependencies
  hive: ^2.2.3
  universal_platform: ^1.0.0+1
  stash: ^4.3.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  stash_test: ^4.3.1