name: stash_shared_preferences_example
description: Demonstrates how to use the stash_shared_preferences plugin
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  stash: ^4.4.1
  stash_shared_preferences:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true