name: stash_sembast_web
version: 4.0.0
publish_to: none
description: >-
  Sembast Web storage extension for the stash caching API. Provides support to store caches
  in a IndexedDB in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_sembast_web

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  sembast: ^3.1.1
  sembast_web: ^2.0.1+1
  #stash: ^3.2.2
  stash:
    path: ../stash
  #stash_sembast: ^4.0.0
  stash_sembast:
    path: ../stash_sembast
dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.3
  #stash_test: ^4.0.0
  stash_test:
    path: ../stash_test
  dependency_validator: ^3.1.0