name: stash_sembast_web
version: 4.0.2
description: >-
  Sembast Web storage extension for the stash API. Provides support to store vaults 
  and caches in a IndexedDB in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_sembast_web

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  sembast: ^3.2.0
  sembast_web: ^2.0.1+1
  stash_sembast: ^4.0.1
  #stash_sembast:
  #  path: ../stash_sembast
dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.0
  stash: ^4.0.1
  #stash:
  #  path: ../stash
  stash_test: ^4.0.0
  #stash_test:
  #  path: ../stash_test