name: stash_sembast_web
version: 4.2.0
description: >-
  Sembast Web storage extension for the stash API. Provides support to store vaults 
  and caches in a IndexedDB in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_sembast_web

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  sembast: ^3.2.0
  sembast_web: ^2.0.1+1
  stash_sembast: ^4.1.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  stash: ^4.1.0
  stash_test: ^4.1.0