name: stash_sembast_web
version: 4.0.0
description: >-
  Sembast Web storage extension for the stash caching API. Provides support to store caches
  in a IndexedDB in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_sembast_web

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  sembast: ^3.1.1
  sembast_web: ^2.0.1+1
  stash_sembast: ^4.0.0-dev.2
  #stash_sembast:
  #  path: ../stash_sembast
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0
  stash: ^4.0.0-dev.2
  #stash:
  #  path: ../stash
  stash_test: ^4.0.0-dev.2
  #stash_test:
  #  path: ../stash_test