name: stash_sqlite
version: 4.6.1
description: >-
   storage extension for the stash API. Provides support to store vaults and 
   caches in a sqlite database in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  drift: ^2.5.0
  stash: ^4.5.2
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.21.4
  # Other dependencies
  lints: ^2.0.1
  build_runner: ^2.3.3
  stash_test: ^4.5.2
  drift_dev: ^2.5.2
