name: stash_sqlite
version: 4.0.2
publish_to: none
description: >-
   storage extension for the stash API. Provides support to store vaults and 
   caches in a sqlite database in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_sqlite

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  drift: ^1.5.0
  #stash: ^4.0.1
  stash:
    path: ../stash
dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
  build_runner: ^2.1.10
  #stash_test: ^4.0.1
  stash_test:
    path: ../stash_test
  drift_dev: ^1.5.2
