name: stash_sqlite
version: 4.0.0
publish_to: none
description: >-
   storage extension for the stash caching API. Provides support to store caches
   in a sqlite database in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_sqlite

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  drift: ^1.1.0
  #stash: ^4.0.0
  stash:
    path: ../stash
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0
  build_runner: ^2.1.7
  #stash_test: ^4.0.0
  stash_test:
    path: ../stash_test
  drift_dev: ^1.1.0
  dependency_validator: ^3.1.2
