name: stash_sqlite
version: 3.2.0
publish_to: none
description: >-
   storage extension for the stash caching API. Provides support to store caches
   in a sqlite database in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_sqlite

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  moor: ^4.4.1
  stash: ^3.2.0
  #stash:
  #  path: ../stash
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
  build_runner: ^2.0.6
  stash_test: ^3.1.0
  #stash_test:
  #  path: ../stash_test
  moor_generator: ^4.4.1
  dependency_validator: ^3.1.0
