name: stash_sqlite
version: 4.4.1
description: >-
   storage extension for the stash API. Provides support to store vaults and 
   caches in a sqlite database in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  drift: ^2.3.0
  stash: ^4.4.1
dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  build_runner: ^2.3.2
  stash_test: ^4.4.1
  drift_dev: ^2.3.2
