name: stash_sembast
version: 3.1.0
description: >-
  Sembast storage extension for the stash caching API. Provides support to store caches
  int the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_sembast

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  sembast: ^3.1.0+2
  sembast_web: ^2.0.0+2
  stash: ^3.1.0
  #stash:
  #  path: ../stash
dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
  stash_test: ^3.1.0
  #stash_test:
  #  path: ../stash_test
  dependency_validator: ^3.1.0