name: stash_sembast
version: 4.3.0
description: >-
  Sembast storage extension for the stash API. Provides support to store vaults and 
  caches in the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash_sembast

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  sembast: ^3.2.0+1
  stash: ^4.3.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.3
  stash_test: ^4.2.0