name: stash
version: 4.0.0.dev.1
publish_to: none
description: >-
  Stash supports the creation of key/value storages through well defined
  abstractions which provide plain or cache driven semantics. Supports a wide
  array of storage backends and integrates with some well known packages in the 
  dart ecosystem.
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  equatable: ^2.0.3
  uuid: ^3.0.5
  clock: ^1.1.0
  async: ^2.8.2
dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.0