name: stash
version: 4.5.0
description: >-
  Stash is a key-value store abstraction with plain and cache driven semantics 
  and support for a pluggable backend architecture.
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.8.0
  clock: ^1.1.1
  async: ^2.10.0
  # Other dependencies
  equatable: ^2.0.5
  uuid: ^3.0.7
dev_dependencies:
  # Flutter shared dependencies
  test: ^1.21.4
  # Other dependencies
  lints: ^2.0.1