name: stash
version: 4.4.1
description: >-
  Stash is a key-value store abstraction with plain and cache driven semantics 
  and support for a pluggable backend architecture.
homepage: https://github.com/ivoleitao/stash
repository: https://github.com/ivoleitao/stash
issue_tracker: https://github.com/ivoleitao/stash/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  # Flutter shared dependencies
  meta: ^1.8.0
  clock: ^1.1.1
  async: ^2.9.0
  # Other dependencies
  equatable: ^2.0.5
  uuid: ^3.0.7
dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0