name: stash
version: 3.0.0-dev.1
description: >-
  Standard caching API for Dart. Defines a common mechanism to create, 
  access, update, and remove information from caches. Provides a in memory
  reference implementation
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.4
  clock: ^1.1.0
  time: ^2.0.0
  async: ^2.6.1
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4