name: stash
version: 4.0.2
description: >-
  Stash is a key-value store abstraction with plain and cache driven semantics 
  and support for a pluggable backend architecture.
homepage: https://github.com/ivoleitao/stash/tree/develop/packages/stash

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  equatable: ^2.0.3
  uuid: ^3.0.6
  clock: ^1.1.0
  async: ^2.8.2
dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1