name: Stash Build

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 8 * * *'
  push:
    branches:
      - develop
    paths:
      - 'melos.yaml'
      - 'packages/**'
      - '.github/workflows/build.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'melos.yaml'
      - 'packages/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Bootstrap
        run: |
          pub global activate melos
          pub global activate pana
          melos bootstrap

      - name: Linter
        run: |
          melos run format
          melos run analyze

      - name: Test
        run: |
          melos run test

      - name: Documentation
        run: |
          melos run doc

      - name: Pana
        run: |
          melos run pana