name: Stash Build

on:
  schedule:
    - cron: '*/30 8 * * *'
  push:
    branches:
      - develop
    paths:
      - 'melos.yaml'
      - 'packages/**'
      - '.github/workflows/build.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'melos.yaml'
      - 'packages/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    steps:
      - name: Set up flutter
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          pub global activate melos
          pub global activate pana

      - name: Bootstrap
        run: |
          melos bootstrap
          
      - name: Linter
        run: |
          melos run format
          melos run analyze

      - name: Test
        run: |
          melos run test

      - name: Documentation
        run: |
          melos run doc

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.7
        with:
          args: --github-token ${{ secrets.GITHUB_TOKEN }} README.md packages/**/README.md

      - name: Calculate scores
        run: |
          melos run pana