name: Build

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/**'
      - '.github/workflows/build.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'packages/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']
        package: ['stash','stash_file'] 

    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install derry
        run: pub global activate derry

      - name: Build
        working-directory: packages/${{ matrix.package }}
        run: derry build

      - name: Verify
        working-directory: packages/${{ matrix.package }}
        run: derry verify
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: ${{ matrix.package }}
          file:  packages/${{ matrix.package }}/coverage/lcov.info