name: Stash Build

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/**'
      - '.github/workflows/build.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'packages/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Bootstrap
        run: |
          pub global activate melos
          melos bootstrap

      - name: Verify
        run: melos run verify