name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 8 * * *'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest' 
          - package: 'stash'
            min-score: 100 

    steps:
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/${{ matrix.package }}
      
      - name: Check scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          SCORE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          if (( $SCORE < ${{ matrix.min-score }} )) then
            exit 1
          fi          