name: Stash CI
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 8 * * *'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        package: ['stash','stash_file','stash_hive']
        include:
          - package: 'stash'
            min-score: 100
          - package: 'stash_file'
            min-score: 50
          - package: 'stash_hive'
            min-score: 100

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: packages/${{ matrix.package }}
      
      - name: Check scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          SCORE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          if (( $SCORE < ${{ matrix.min-score }} )); then
            echo "Package score ($SCORE) is less than the minium configured score (${{ matrix.min-score }})"
            exit 1
          else
            echo "Package score ($SCORE) OK!"
          fi

      - name: Coverage
        working-directory: packages/${{ matrix.package }}
        run: |
          dart test --concurrency=1 --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file:  packages/${{ matrix.package }}/coverage/lcov.inf