name: Dart CI

on:
  schedule:
    - cron: '*/30 8 * * *'
  push:
    branches:
      - develop
    paths:
      - 'melos.yaml'
      - 'packages/**'
      - '.github/workflows/dart-ci.yml'

  pull_request:
    branches:
      - develop
    paths:
      - 'melos.yaml'
      - 'packages/**'
      - '.github/workflows/dart-ci.yml'

jobs:
  ci:
    name: Dart CI

    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev -y
          bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)

      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          pub global activate melos

      - name: Bootstrap
        run: |
          melos bootstrap
          
      - name: Linter
        run: |
          melos run dependency-validator
          melos run format
          melos run analyze

      - name: Test
        run: |
          melos run test

      - name: Documentation
        run: |
          melos run doc

      - name: Verify
        run: |
          melos run verify