name: Dart Coverage

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**'
      - '.github/workflows/dart-coverage.yml'

jobs:
  coverage:
    name: Dart Coverage

    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install libraries
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev -y
          bash <(curl -s https://raw.githubusercontent.com/objectbox/objectbox-dart/main/install.sh)

      - name: Set up dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          pub global activate melos

      - name: Bootstrap
        run: |
          melos bootstrap

      - name: Coverage
        run: |
          melos run coverage
          melos run codecov