name: Stash Publish

on:
  push:
    branches:
      - master
    paths:
      - 'packages/**'
      - '.github/workflows/publish.yml'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        sdk: ['stable']

    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Bootstrap
        run: |
          pub global activate melos
          melos bootstrap
          echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json

      - name: Publish
        run: melos publish